language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
before_install:
- echo $TRAVIS_BUILD_DIR
- sudo apt-get -qq update
- sudo apt-get -y install build-essential
- sudo apt-get -y build-dep zlib
- sudo apt-get -y build-dep openssl
- sudo apt-get -y build-dep libssh2
- sudo apt-get -y build-dep curl
- sudo apt-get -y install aria2
- mkdir $HOME/sources
- mkdir $HOME/libs
- cd $HOME/libs
- "mkdir {zlib,openssl,libssh2,curl}"
- mkdir $HOME/libs/openssl/lib
- mkdir $HOME/libs/openssl/lib/pkgconfig
- cd $HOME/sources
- apt-get -y source zlib
- apt-get -y source openssl
- apt-get -y source libssh2
- aria2c -V --check-certificate=false http://curl.haxx.se/metalink.cgi?curl=tar.gz
- tar -xvf curl-*.tar.gz

install:
- export LIBS+=-ldl
- cd $HOME/sources/zlib-*
- ./configure --prefix=$HOME/libs/zlib
- make
- make install
- cd $HOME/sources/openssl-*
- ./config -fPIC no-asm --prefix=$HOME/libs/openssl --openssldir=$HOME/libs/openssl
- make
- cp *.a $HOME/libs/openssl/lib
- cp *.pc $HOME/libs/openssl/lib/pkgconfig
- cp -r include $HOME/libs/openssl
- cd $HOME/sources/libssh2-*
- ./configure --with-openssl --with-libssl-prefix=$HOME/libs/openssl --with-libz --with-libz-prefix=$HOME/libs/zlib --without-libgcrypt --enable-static --prefix=$HOME/libs/libssh2
- make
- make install
- cd $HOME/sources/curl-*
- ./configure --with-ssl=$HOME/libs/openssl --with-zlib=$HOME/libs/zlib --with-libssh2=$HOME/libs/libssh2 --disable-rtsp --without-librtmp --disable-manual --disable-ldaps --disable-ldap --disable-sspi --without-libidn --enable-static --prefix=$HOME/libs/curl
- make
- make install
- cd $TRAVIS_BUILD_DIR