language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
before_install:
- sudo apt-get -qq update
- sudo apt-get -y install build-essential
- sudo apt-get -y build-dep zlib
- sudo apt-get -y build-dep openssl
- sudo apt-get -y build-dep libssh2
- sudo apt-get -y build-dep curl
- mkdir $HOME/sources
- mkdir $HOME/libs
- cd $HOME/libs
- "sudo mkdir {zlib,openssl,libssh2,curl}"
- cd $HOME/sources
- export LIBS+=-ldl
- apt-get -y source zlib
- apt-get -y source openssl
- apt-get -y source libssh2
- apt-get -y source curl

install:
- cd $HOME/sources/zlib-*
- ./configure --prefix=$HOME/sources/libs/zlib
- sudo make
- sudo make install
- cd $HOME/sources/openssl-*
- ./config no-asm -fPIC --prefix=$HOME/sources/libs/openssl --openssldir=$HOME/sources/libs/openssl
- sudo make
- sudo make install
- cd $HOME/sources/libssh2-*
- ./configure --with-openssl --with-libssl-prefix=$HOME/sources/libs/openssl --with-libz --with-libz-prefix=$HOME/sources/libs/zlib --without-libgcrypt --enable-static --prefix=$HOME/sources/libs/libssh2
- sudo make
- sudo make install
- cd $HOME/sources/curl-*
- ./configure --with-ssl=$HOME/sources/libs/openssl --with-zlib=$HOME/sources/libs/zlib --with-libssh2=$HOME/sources/libs/libssh2 --disable-rtsp --disable-ldaps --disable-ldap --disable-sspi --without-libidn --enable-static --prefix=$HOME/sources/libs/curl
- sudo make
- sudo make install