language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
before_install:
- echo $TRAVIS_BUILD_DIR
- sudo apt-get -qq update
- sudo apt-get -y install build-essential
- sudo apt-get -y build-dep zlib
- sudo apt-get -y build-dep openssl
- sudo apt-get -y build-dep libssh2
- sudo apt-get -y build-dep curl
- sudo apt-get -y install aria2
- sudo apt-get -y install gcc-multilib g++-multilib
- mkdir $HOME/sourcemod
- mkdir $HOME/mmsource-1.10
- mkdir $HOME/sources
- mkdir $HOME/libs
- cd $HOME/libs
- "mkdir {zlib,openssl,libssh2,curl}"
- cd $HOME/sources
- apt-get -y source zlib
- apt-get -y source openssl
- apt-get -y source libssh2
- aria2c -V --check-certificate=false http://curl.haxx.se/metalink.cgi?curl=tar.gz
- tar -xvf curl-*.tar.gz

install:
- export LIBS+=-ldl
- export CFLAGS=-m32
- export CPPFLAGS=-m32
- cd $HOME/sources/zlib-*
- setarch i386 ./configure --prefix=$HOME/libs/zlib
- setarch i386 make
- make install
- cd $HOME/sources/openssl-*
- setarch i386 ./config -fPIC no-asm --prefix=$HOME/libs/openssl --openssldir=$HOME/libs/openssl -m32
- setarch i386 make
- make install_sw
- cd $HOME/sources/libssh2-*
- setarch i386 ./configure --with-openssl --with-libssl-prefix=$HOME/libs/openssl --with-libz --with-libz-prefix=$HOME/libs/zlib --without-libgcrypt --enable-static --prefix=$HOME/libs/libssh2
- setarch i386 make
- make install
- cd $HOME/sources/curl-*
- setarch i386 ./configure --with-ssl=$HOME/libs/openssl --with-zlib=$HOME/libs/zlib --with-libssh2=$HOME/libs/libssh2 --disable-rtsp --without-librtmp --disable-manual --disable-ldaps --disable-ldap --disable-sspi --without-libidn --enable-static --prefix=$HOME/libs/curl
- setarch i386 make
- make install
- cd $HOME/sourcemod
- git clone -b 1.7-dev --single-branch https://github.com/alliedmodders/sourcemod.git .
- cp -r $TRAVIS_BUILD_DIR $HOME/sourcemod/extensions/
- cd $HOME/mmsource-1.10
- git clone -b 1.10-dev --single-branch https://github.com/alliedmodders/metamod-source.git .

script:
- cd $HOME/sourcemod/extensions/Sourcemod-Curl-Extension
- setarch i386 make